name: Auto-Merge PR (Owner Only)
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner
    steps:
      - name: Check if PR is mergeable
        id: check-mergeable
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            return pr.data.mergeable;

      - name: Auto-Merge PR
        if: steps.check-mergeable.outputs.result == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                merge_method: 'merge'
              });
              console.log('PR успешно смержен!');
            } catch (error) {
              console.error('Ошибка:', error.message);
            }
